owner: tiekoetter # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository
assignees:
  - tiekoetter
user-agent: Tiekoetter.NET Uptime Checker @ status.tiekoetter.cloud

sites:
  - name: Tiekoetter.NET
    url: https://www.tiekoetter.net
    headers:
      - 'User-Agent: Tiekoetter.NET Uptime Checker @ status.tiekoetter.cloud'
  - name: AS.Tiekoetter.NET (AS208694)
    url: https://www.as.tiekoetter.net
    headers:
      - 'User-Agent: Tiekoetter.NET Uptime Checker @ status.tiekoetter.cloud'
  - name: Tiekoetter.com
    url: https://www.tiekoetter.com
    headers:
      - 'User-Agent: Tiekoetter.NET Uptime Checker @ status.tiekoetter.cloud'
  - name: CDN (tiekoetter.cloud)
    url: https://tiekoettercom-cdn.tiekoetter.cloud/cdn/test.txt
    headers:
      - 'User-Agent: Tiekoetter.NET Uptime Checker @ status.tiekoetter.cloud'
  - name: ns1.tiekoetter.net
    check: "tcp-ping"
    url: ns1.tiekoetter.net
    port: 53
    maxResponseTime: 5000
  - name: ns2.tiekoetter.net
    check: "tcp-ping"
    url: ns2.tiekoetter.net
    port: 53
    maxResponseTime: 5000
  - name: ns3.tiekoetter.net
    check: "tcp-ping"
    url: ns3.tiekoetter.net
    port: 53
    maxResponseTime: 5000
  - name: ns4.tiekoetter.net
    check: "tcp-ping"
    url: ns4.tiekoetter.net
    port: 53
    maxResponseTime: 5000
  - name: searx.tiekoetter.com
    url: https://searx.tiekoetter.com
    headers:
      - 'User-Agent: Tiekoetter.NET Uptime Checker @ status.tiekoetter.cloud'
  - name: invidious.tiekoetter.com
    url: https://invidious.tiekoetter.com
    headers:
      - 'User-Agent: Tiekoetter.NET Uptime Checker @ status.tiekoetter.cloud'
  - name: forum.iekoetter.com
    url: https://forum.tiekoetter.com
    headers:
      - 'User-Agent: Tiekoetter.NET Uptime Checker @ status.tiekoetter.cloud'
  - name: bin.tiekoetter.com
    url: https://bin.tiekoetter.com
    headers:
      - 'User-Agent: Tiekoetter.NET Uptime Checker @ status.tiekoetter.cloud'
  - name: wikiless.tiekoetter.com
    url: https://wikiless.tiekoetter.com
    headers:
      - 'User-Agent: Tiekoetter.NET Uptime Checker @ status.tiekoetter.cloud'
  - name: nitter.tiekoetter.com
    url: https://nitter.tiekoetter.com
    headers:
      - 'User-Agent: Tiekoetter.NET Uptime Checker @ status.tiekoetter.cloud'
  - name: redlib.tiekoetter.com
    url: https://redlib.tiekoetter.com
    headers:
      - 'User-Agent: Tiekoetter.NET Uptime Checker @ status.tiekoetter.cloud'
  - name: translate.tiekoetter.com
    url: https://translate.tiekoetter.com
    headers:
      - 'User-Agent: Tiekoetter.NET Uptime Checker @ status.tiekoetter.cloud'
  - name: lt27.de
    url: https://lt27.de
    headers:
      - 'User-Agent: Tiekoetter.NET Uptime Checker @ status.tiekoetter.cloud'
  - name: searx-instances.tiekoetter.com
    url: https://searx-instances.tiekoetter.com
    headers:
      - 'User-Agent: Tiekoetter.NET Uptime Checker @ status.tiekoetter.cloud'
  - name: leontiekoetter.de
    url: https://www.leontiekoetter.de
    headers:
      - 'User-Agent: Tiekoetter.NET Uptime Checker @ status.tiekoetter.cloud'
  - name: craftsmany.net
    url: https://www.craftsmany.net
    headers:
      - 'User-Agent: Tiekoetter.NET Uptime Checker @ status.tiekoetter.cloud'
  - name: ts.craftsmany.net TeamSpeak 3 Server
    check: "udp-ping"
    url: ts.craftsmany.net
    port: 9988
  - name: "fehling.me [Owner: Luke Fehling]"
    url: https://fehling.me
    headers:
      - 'User-Agent: Tiekoetter.NET Uptime Checker @ status.tiekoetter.cloud'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  introTitle: "Tiekoetter.NET Status & Uptime monitoring"
  introMessage: This status page lists all services provided and / or hosted by Tiekoetter.NET and checks their uptime every 5 minutes.
  cname: status.tiekoetter.cloud
  favicon: https://tiekoettercom-cdn.tiekoetter.cloud/wp-content/uploads/2020/06/tiekoetter-300x300.png
  logoUrl: https://tiekoettercom-cdn.tiekoetter.cloud/wp-content/uploads/2020/06/tiekoetter-300x300.png
  theme: light
  name: Tiekoetter.NET Status
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Tiekoetter.com
      href: https://www.tiekoetter.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 0 * * *"

commitMessages:
  commitAuthorName: "Tiekoetter Bot"
  commitAuthorEmail: "github-bot@tiekoetter.com"
